/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.whatsapp;

import java.awt.Desktop;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URLEncoder;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mkpol
 */
public class PantallaWhatsapp extends javax.swing.JFrame {

    /**
     * Creates new form PantallaWhatsapp
     */
    public PantallaWhatsapp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnWhatsapp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        txtTelefono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnWhatsapp.setText("WHATSAPP");
        btnWhatsapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWhatsappActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(btnWhatsapp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(txtTelefono))))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnWhatsapp)
                .addGap(117, 117, 117))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWhatsappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWhatsappActionPerformed
        int fila = 2;
    if (fila == -1) {
        JOptionPane.showMessageDialog(null, "Seleccione un registro para cargar o una plantilla");
    } else {
        if(!txtArea.getText().isEmpty()) {
            String telefono = txtTelefono.getText();
            String mensaje = txtArea.getText();
            //System.out.println("URL de WhatsApp: " + urlApiWhatsApp); // Agregar una impresión para verificar la URL generada
            if(java.awt.Desktop.isDesktopSupported()) {
                java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
                if(desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
                    try {
                        String textoCodificado = URLEncoder.encode(mensaje, "UTF-8");
                        String urlApiWhatsApp = "whatsapp://send?phone=521" + telefono + "&text=" + textoCodificado;
                        //java.net.URI url1 = new java.net.URI(urlApiWhatsApp);
                        //desktop.browse(url1);
                        Desktop.getDesktop().browse(URI.create(urlApiWhatsApp));
                        Desktop.getDesktop().browse(URI.create(urlApiWhatsApp));
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "Error en " + ex, "Advertencia", JOptionPane.WARNING_MESSAGE);
                        ex.printStackTrace(); // Agregar una impresión del seguimiento de la pila del error
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null, "El escritorio no lo soporta");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una plantilla");
        }
    }
    }//GEN-LAST:event_btnWhatsappActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnWhatsapp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
